language: go
go:
  - 1.4
install:
  - go get github.com/astaxie/beego
  - go get github.com/smartystreets/goconvey/convey
  - mv $HOME/gopath/src/github.com/kofj/Shadowsocks-Service-Pack $HOME/gopath/src
  - cd $HOME/gopath/src/Shadowsocks-Service-Pack
  - go install ./Panel
